image: mcr.microsoft.com/dotnet/aspnet:6.0

stages:
  - build
  - test
  - deploy

before_script:
  - $PSVersionTable.PSVersion
  - dotnet --version
  - nuget help | select-string Version

build job:
  stage: build
  script:
    - dotnet build -c Release
  tags:
    - windows
  only:
    - merge_requests
    - master
  artifacts:
    paths:
      - path/to/binaries
