image: docker:20.10.13

services:
  - docker:20.10.13-dind

stages:
  - test
  - deploy

test:
  stage: test
  only:
    - deploy
    - master
  script:
    - echo run tests in this section

before_script:
  - docker info
  - apk update
  - apk upgrade
  - apk add docker-compose

step-deploy-prod:
  stage: deploy
  only:
    - master
  script:
    - uname -a
    - docker-compose build --no-cache
    - docker-compose up -d
  environment:
    name: deploy
    url: http://213.178.155.140
  when: manual
