image: mcr.microsoft.com/dotnet/aspnet:6.0

stages:
  - build
  - test
  - deploy

before_script:
  - $PSVersionTable.PSVersion
  - dotnet --version
  - nuget help | select-string Version

dummy job on windows:
  script:
    - echo ok
  tags:
    - windows
