image: docker:20.10.13

services:
  - docker:20.10.13-dind

stages:
  - test
  - deploy

test:
  stage: test
  only:
    - deploy
    - master
  script:
    - echo run tests in this section

step-deploy-prod:
  stage: deploy
  only:
    - master
  script:
    - apk add --no-cache docker-compose
    - docker-compose build --no-cache
    - docker-compose up -d
  environment: master
  when: manual
