image: docker

service:
  - docker:dind

stages:
  - test
  - deploy

test:
  stage: test
  only:
    - deploy
    - master
  script:
    - echo run tests in this section

deploy:
  stage: deploy
  only:
    - master
  script:
    - docker-compose up -d --build
  environment: master
  when: manual
