version: '3.4'

services:
  petitionapp.api:
    image: ${DOCKER_REGISTRY-}petitionappapi
    build:
      context: .
      dockerfile: PetitionApp.API/Dockerfile
    ports:
      - 5000:80
  nginx:
    image: nginx:latest
    volumes:
      - ./NGINX/nginx.conf:/etc/nginx/nginx.conf
    ports:
     - 8001:80
